### ISSUE TITLE
Does not work on GPD Win 4?

### ISSUE THREAD

**Issue by kingo132** [matega/win-max-2-fan-control#1]
Do you know how to make it work on GPD Win 4? Thank you so much!

**Comment by kingo132** [comment]
I made it. Thanks for your repository!

```c
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/cppFiles/main.cc to edit this template
 */

/* 
 * File:   main.cpp
 * Author: matega
 *
 * Created on 16 February 2023, 10:37
 */

#include <cstdlib>
#include <sys/io.h>
#include <string>
#include <iostream>

using namespace std;

/*
 * 
 */
void ECRamWriteWin4(unsigned short address, unsigned char data) {
    unsigned char reg_addr = 46;
    unsigned char reg_data = 47;
    
    unsigned char addr_upper = (unsigned char)(address >> 8 & 255);
    unsigned char addr_lower = (unsigned char)(address & 255);
    
    outb(46, reg_addr);
    outb(17, reg_data);
    outb(47, reg_addr);
    outb(addr_upper, reg_data);
    
    outb(46, reg_addr);
    outb(16, reg_data);
    outb(47, reg_addr);
    outb(addr_lower, reg_data);
    
    outb(46, reg_addr);
    outb(18, reg_data);
    outb(47, reg_addr);
    outb(data, reg_data);
}

unsigned char ECRamReadWin4(unsigned short address) {
    unsigned char reg_addr = 46;
    unsigned char reg_data = 47;
    
    unsigned char addr_upper = (unsigned char)(address >> 8 & 255);
    unsigned char addr_lower = (unsigned char)(address & 255);
    
    outb(46, reg_addr);
    outb(17, reg_data);
    outb(47, reg_addr);
    outb(addr_upper, reg_data);
    
    outb(46, reg_addr);
    outb(16, reg_data);
    outb(47, reg_addr);
    outb(addr_lower, reg_data);
    
    outb(46, reg_addr);
    outb(18, reg_data);
    outb(47, reg_addr);
    return inb(reg_data);
}

void InitECWin4() {
    if (ECRamReadWin4(8192) == 85) {
	unsigned char b = ECRamReadWin4(4192);
	b = (unsigned char)(b | 0x80u);
	ECRamWriteWin4(4192, b);
    }
}

float ReadFanSpeedWin4() {
    if (ECRamReadWin4(6209) != 127) {
        ECRamWriteWin4(6209, 127);
    }
    unsigned char b = ECRamReadWin4(51329);
    return (ECRamReadWin4(51328) << 8) | b;
}

int main(int argc, char** argv) {
    #define GPDW2_ECRAM 46

    if(argc != 2) exit(-1);
    
    int x = atoi(argv[1]);
    
    if(argv[1][0] != 'a' && (x < 0 || x > 255)) {
        exit(-1);
    } 

    if (ioperm(GPDW2_ECRAM, 2, 1)) {
        cout << "Failed to request access\n";
        exit(-1);
     /* handle error */
    }
    
    if (argv[1][0] == 'g') {
        //cout << "Get fan speed: " << ReadFanSpeedWin4() << endl;
	float num = ReadFanSpeedWin4();
	if (num == 0) {
	    InitECWin4();
	}
        cout << num << endl;
    } else if(argv[1][0] == 'a') {
        cout << "Setting auto fan" << endl;
        ECRamWriteWin4(49937,0);
    } else {
        cout << "Setting fan speed " << to_string(x) << endl;
        ECRamWriteWin4(49937,x);
    }

    if (ioperm(GPDW2_ECRAM, 2, 0)) {
        cout << "Failed to release access\n";
        exit(-1);
     /* handle error */
    }

    return 0;
}
```

**Comment by SunRain** [comment]
> I made it. Thanks for your repository!
> 
> ```c
> /*
>  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
>  * Click nbfs://nbhost/SystemFileSystem/Templates/cppFiles/main.cc to edit this template
>  */
> 
> /* 
>  * File:   main.cpp
>  * Author: matega
>  *
>  * Created on 16 February 2023, 10:37
>  */
> 
> #include <cstdlib>
> #include <sys/io.h>
> #include <string>
> #include <iostream>
> 
> using namespace std;
> 
> /*
>  * 
>  */
> void ECRamWriteWin4(unsigned short address, unsigned char data) {
>     unsigned char reg_addr = 46;
>     unsigned char reg_data = 47;
>     
>     unsigned char addr_upper = (unsigned char)(address >> 8 & 255);
>     unsigned char addr_lower = (unsigned char)(address & 255);
>     
>     outb(46, reg_addr);
>     outb(17, reg_data);
>     outb(47, reg_addr);
>     outb(addr_upper, reg_data);
>     
>     outb(46, reg_addr);
>     outb(16, reg_data);
>     outb(47, reg_addr);
>     outb(addr_lower, reg_data);
>     
>     outb(46, reg_addr);
>     outb(18, reg_data);
>     outb(47, reg_addr);
>     outb(data, reg_data);
> }
> 
> unsigned char ECRamReadWin4(unsigned short address) {
>     unsigned char reg_addr = 46;
>     unsigned char reg_data = 47;
>     
>     unsigned char addr_upper = (unsigned char)(address >> 8 & 255);
>     unsigned char addr_lower = (unsigned char)(address & 255);
>     
>     outb(46, reg_addr);
>     outb(17, reg_data);
>     outb(47, reg_addr);
>     outb(addr_upper, reg_data);
>     
>     outb(46, reg_addr);
>     outb(16, reg_data);
>     outb(47, reg_addr);
>     outb(addr_lower, reg_data);
>     
>     outb(46, reg_addr);
>     outb(18, reg_data);
>     outb(47, reg_addr);
>     return inb(reg_data);
> }
> 
> void InitECWin4() {
>     if (ECRamReadWin4(8192) == 85) {
> 	unsigned char b = ECRamReadWin4(4192);
> 	b = (unsigned char)(b | 0x80u);
> 	ECRamWriteWin4(4192, b);
>     }
> }
> 
> float ReadFanSpeedWin4() {
>     if (ECRamReadWin4(6209) != 127) {
>         ECRamWriteWin4(6209, 127);
>     }
>     unsigned char b = ECRamReadWin4(51329);
>     return (ECRamReadWin4(51328) << 8) | b;
> }
> 
> int main(int argc, char** argv) {
>     #define GPDW2_ECRAM 46
> 
>     if(argc != 2) exit(-1);
>     
>     int x = atoi(argv[1]);
>     
>     if(argv[1][0] != 'a' && (x < 0 || x > 255)) {
>         exit(-1);
>     } 
> 
>     if (ioperm(GPDW2_ECRAM, 2, 1)) {
>         cout << "Failed to request access\n";
>         exit(-1);
>      /* handle error */
>     }
>     
>     if (argv[1][0] == 'g') {
>         //cout << "Get fan speed: " << ReadFanSpeedWin4() << endl;
> 	float num = ReadFanSpeedWin4();
> 	if (num == 0) {
> 	    InitECWin4();
> 	}
>         cout << num << endl;
>     } else if(argv[1][0] == 'a') {
>         cout << "Setting auto fan" << endl;
>         ECRamWriteWin4(49937,0);
>     } else {
>         cout << "Setting fan speed " << to_string(x) << endl;
>         ECRamWriteWin4(49937,x);
>     }
> 
>     if (ioperm(GPDW2_ECRAM, 2, 0)) {
>         cout << "Failed to release access\n";
>         exit(-1);
>      /* handle error */
>     }
> 
>     return 0;
> }
> ```

你好,这段控制EC的代码在GPD-win4上是能正确运行的吗，这几天在找win4在linux下控制风扇的方法，偶然发现了这个issue.
另外，我发现了个https://github.com/Gawah/PowerControl,基于archlinux的HoloIso的插件，但是看issue似乎有些问题。
我不是很懂TypeScript,不知道是否对你有帮助。

**Comment by kingo132** [comment]
可以运行啊，很完美
